opencv_createsamples.exe -info source_positive_sample1_pic\positive_sample1.txt -vec positive_samples_vec\positive_sample1_self.vec -h 50 -w 50 -num 4 -show
opencv_createsamples.exe -info source_positive_sample2_pic\positive_sample2.txt -vec positive_samples_vec\positive_sample2_self.vec -h 50 -w 50 -num 4 -show
opencv_createsamples.exe -img source_positive_sample1_pic\1.jpg -vec positive_samples_vec\positive_sample1_1.vec -h 50 -w 50 -bg negative_samples_pic\negative_samples.txt -num 125 -maxxangle 1.1 -maxyangle 1.1 -maxzangle 0.5 -bgcolor 0 -bgthresh 0 -maxidev 40 -show
opencv_createsamples.exe -img source_positive_sample1_pic\2.jpg -vec positive_samples_vec\positive_sample1_2.vec -h 50 -w 50 -bg negative_samples_pic\negative_samples.txt -num 125 -maxxangle 1.1 -maxyangle 1.1 -maxzangle 0.5 -bgcolor 0 -bgthresh 0 -maxidev 40 -show
opencv_createsamples.exe -img source_positive_sample1_pic\3.jpg -vec positive_samples_vec\positive_sample1_3.vec -h 50 -w 50 -bg negative_samples_pic\negative_samples.txt -num 125 -maxxangle 1.1 -maxyangle 1.1 -maxzangle 0.5 -bgcolor 0 -bgthresh 0 -maxidev 40 -show
opencv_createsamples.exe -img source_positive_sample1_pic\4.jpg -vec positive_samples_vec\positive_sample1_4.vec -h 50 -w 50 -bg negative_samples_pic\negative_samples.txt -num 125 -maxxangle 1.1 -maxyangle 1.1 -maxzangle 0.5 -bgcolor 0 -bgthresh 0 -maxidev 40 -show
opencv_createsamples.exe -img source_positive_sample2_pic\1.jpg -vec positive_samples_vec\positive_sample2_1.vec -h 50 -w 50 -bg negative_samples_pic\negative_samples.txt -num 125 -maxxangle 1.1 -maxyangle 1.1 -maxzangle 0.5 -bgcolor 0 -bgthresh 0 -maxidev 40 -show
opencv_createsamples.exe -img source_positive_sample2_pic\2.jpg -vec positive_samples_vec\positive_sample2_2.vec -h 50 -w 50 -bg negative_samples_pic\negative_samples.txt -num 125 -maxxangle 1.1 -maxyangle 1.1 -maxzangle 0.5 -bgcolor 0 -bgthresh 0 -maxidev 40 -show
opencv_createsamples.exe -img source_positive_sample2_pic\3.jpg -vec positive_samples_vec\positive_sample2_3.vec -h 50 -w 50 -bg negative_samples_pic\negative_samples.txt -num 125 -maxxangle 1.1 -maxyangle 1.1 -maxzangle 0.5 -bgcolor 0 -bgthresh 0 -maxidev 40 -show
opencv_createsamples.exe -img source_positive_sample2_pic\4.jpg -vec positive_samples_vec\positive_sample2_4.vec -h 50 -w 50 -bg negative_samples_pic\negative_samples.txt -num 125 -maxxangle 1.1 -maxyangle 1.1 -maxzangle 0.5 -bgcolor 0 -bgthresh 0 -maxidev 40 -show
oppause